services:
  # ====================
  # API Service
  # ====================
  api:
    build:
      context: ./api
      target: development       # dev stage in your Dockerfile
    image: api:latest
    environment:
      - NODE_ENV=development
    ports:
      - "5000:3000"
    volumes:
      - ./api:/app:cached                 # mount source code for hot reload
      - api_node_modules:/app/node_modules
    command: npx nodemon --watch src --ext ts,js,json --ignore node_modules --legacy-watch src/index.js

  # ====================
  # Frontend Service
  # ====================

  frontend:
    build:
      context: ./chit-chat-ui
      target: development
    image: frontend:latest
    environment:
      - NODE_ENV=development
      - HOST=0.0.0.0
    ports:
      - "8000:8000"
    volumes:
      - ./chit-chat-ui:/app:cached
      - frontend_node_modules:/app/node_modules
    command: npm run dev

# ====================
# Named volumes
# ====================
volumes:
  api_node_modules:
  frontend_node_modules:
