services:
  # API Service
  api:
    build:
      context: ./api
    image: api:latest
    environment:
      - NODE_ENV=development
    ports:
      - "3000:3000"
    volumes:
      - ./api:/app:cached
      - api_node_modules:/app/node_modules
    command: npx ts-node src/main.ts

  # Frontend Service
  frontend:
    build:
      context: ./chit-chat-ui
    image: frontend:latest
    environment:
      - NODE_ENV=development
      - HOST=0.0.0.0
    ports:
      - "8000:8000"
    volumes:
      - frontend_node_modules:/app/node_modules
      - ./chit-chat-ui:/app:cached
    command: npm run dev

volumes:
  api_node_modules:
  frontend_node_modules:
