name: Playwright E2E Tests

# on:
#   workflow_run:
#     workflows: ["Code Scanning"]
#     types: [completed]

on:
  pull_request:
    branches: [ jordyn/githubactions ]
  push:
    branches: [ jordyn/githubactions ]

jobs:
  e2e-tests:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Pull and run backend image
        run: |
          docker pull ghcr.io/bumetcs673/chat-backend:dev
          docker run -d -p 5000:5000 --name chat-backend ghcr.io/bumetcs673/chat-backend:dev
          until curl -f http://localhost:5000/health; do sleep 2; done

      - name: Pull and run frontend image
        run: |
          docker pull ghcr.io/bumetcs673/chat-frontend:dev
          docker run -d -p 80:80 --name chat-frontend ghcr.io/bumetcs673/chat-frontend:dev
          until curl -f http://localhost; do sleep 2; done

      - name: Install dependencies
        run: npm install
        working-directory: ./tests/e2e

      - name: Run Playwright E2E tests
        run: npx playwright test --config=playwright.config.ts --headless
        working-directory: ./tests/e2e

      - name: Stop Docker containers
        run: |
          docker stop chat-backend chat-frontend
          docker rm chat-backend chat-frontend