name: Playwright E2E Tests

# on:
#   workflow_run:
#     workflows: ["Code Scanning"]
#     types: [completed]

on:
  pull_request:
    branches: [ jordyn/githubactions ]
  push:
    branches: [ jordyn/githubactions ]

jobs:
  e2e-tests:
    runs-on: ubuntu-latest

    services:
      backend:
        image: ghcr.io/bumetcs673/chat-backend:dev
        ports:
          - 5000:5000
        options: >-
          --health-cmd "curl -f http://localhost:5000/health || exit 1"
          --health-interval 5s
          --health-timeout 2s
          --health-retries 10

      frontend:
        image: ghcr.io/bumetcs673/chat-frontend:dev
        ports:
          - 80:80
        options: >-
          --health-cmd "curl -f http://localhost || exit 1"
          --health-interval 5s
          --health-timeout 2s
          --health-retries 10

    steps:
      - uses: actions/checkout@v4

      # Install Playwright and system dependencies
      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: 20

      - name: Install Playwright dependencies
        run: |
          npm ci
          npx playwright install --with-deps
        working-directory: ./tests/e2e

      # Run Playwright tests
      - name: Run E2E Tests
        env:
          BASE_URL: http://frontend
          API_URL: http://backend:5000
        run: npx playwright test --headless
        working-directory: ./tests/e2e