name: Playwright E2E Tests

# on:
#   workflow_run:
#     workflows: ["Code Scanning"]
#     types: [completed]

on:
  pull_request:
    branches: [ jordyn/githubactions ]
  push:
    branches: [ jordyn/githubactions ]

jobs:
  e2e-tests:
    runs-on: ubuntu-latest

    services:
      backend:
        image: ghcr.io/bumetcs673/chat-backend:dev
        ports:
          - 5000:5000
        options: >-
          --health-cmd "curl -f http://localhost:5000/health || exit 1"
          --health-interval 5s
          --health-timeout 2s
          --health-retries 10

      frontend:
        image: ghcr.io/bumetcs673/chat-frontend:dev
        ports:
          - 80:80
        options: >-
          --health-cmd "curl -f http://localhost || exit 1"
          --health-interval 5s
          --health-timeout 2s
          --health-retries 10

    steps:
      - uses: actions/checkout@v4

      # Optional: log in to GHCR if images are private
      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Install Playwright dependencies
        run: npm install
        working-directory: ./tests/e2e

      - name: Run Playwright E2E tests
        run: npx playwright test --config=playwright.config.ts --headless
        working-directory: ./tests/e2e