name: Build and Push Docker Images to GHCR

# on:
#   workflow_run:
#     workflows: ["Code Scanning"]
#     types: [completed]

on:
  pull_request:
    branches: [ jordyn/githubactions ]
  push:
    branches: [ jordyn/githubactions ]

jobs:
  build-and-push:
    runs-on: ubuntu-latest
    env:
      OWNER_LOWER: ${{ github.repository_owner }}
    steps:
      - uses: actions/checkout@v4

      - name: Set lowercase owner
        id: owner
        run: |
          echo "OWNER_LOWER=$(echo $GITHUB_REPOSITORY_OWNER | tr '[:upper:]' '[:lower:]')" >> $GITHUB_ENV


      - name: Log in to GHCR
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}

      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v3

      # Backend
      - name: Build and push backend image
        uses: docker/build-push-action@v5
        with:
          context: ./api
          file: ./api/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ env.OWNER_LOWER }}/chat-backend:dev
            ghcr.io/${{ env.OWNER_LOWER }}/chat-backend:${{ github.sha }}

      # Frontend
      - name: Build and push frontend image
        uses: docker/build-push-action@v5
        with:
          context: ./chit-chat-ui
          file: ./chit-chat-ui/Dockerfile
          push: true
          tags: |
            ghcr.io/${{ env.OWNER_LOWER }}/chat-frontend:dev
            ghcr.io/${{ env.OWNER_LOWER }}/chat-frontend:${{ github.sha }}